#!/usr/bin/python

import os

bullfuckingshit = []

while True:
    os.system("ps axo pid >> /tmp/pslist; echo $? >> /tmp/pslist")
    for i in open("/tmp/pslist", "r").read().split("\n"):
        if not i in bullfuckingshit:
            print(i)
            os.system("cynject " + i + " /Library/Frameworks/CydiaSubstrate.framework/Libraries/SubstrateLoader.dylib & echo $? > /tmp/pslist")
            bullfuckingshit.append(i)
